#!/usr/bin/env bash
set -euo pipefail
project_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
printf -v command '%q ' "$project_dir/run" "$@"
exec nix-shell "$project_dir/shell.nix" --run "$command"
